# Render.com Deployment Configuration
version: 1
services:
  - type: web
    name: playschool-backend
    env: java
    buildCommand: mvn clean package -DskipTests -q
    startCommand: java -Xmx512m -Dspring.profiles.active=cloud -Dserver.port=$PORT -Djava.security.egd=file:/dev/./urandom -jar target/management-backend-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: cloud
      - key: DATABASE_URL
        fromDatabase:
          name: playschool-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 86400000
      - key: CORS_ALLOWED_ORIGINS
        value: https://playschool-a2z.netlify.app,http://localhost:3000,http://localhost:4200
