# Render.com Deployment Configuration
version: 1
services:
  - type: web
    name: playschool-backend
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/management-backend-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: DB_HOST
        value: dpg-d1p425bipnbc73fkdfa0-a
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: educare
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: dsyarysXiegZNRVVXX77fttA9bVmm3ew
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 86400000
      - key: CORS_ALLOWED_ORIGINS
        value: https://playschool-a2z.netlify.app
