# Render.com Deployment Configuration
version: 1
services:
  - type: web
    name: playschool-backend
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/management-backend-0.0.1-SNAPSHOT.jar --spring.profiles.active=cloud
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgresql://root:dsyarysXiegZNRVVXX77fttA9bVmm3ew@dpg-d1p425bipnbc73fkdfa0-a/educare
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: dsyarysXiegZNRVVXX77fttA9bVmm3ew
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_PROFILES_ACTIVE
        value: cloud
      - key: ALLOWED_ORIGINS
        value: https://your-frontend-domain.com
